Switch to vanilla Go sqlite package (#117)
mattn/go-sqlite3 fails with the following linker error on new macs.

# github.com/google/ax/internal/controller.test
/usr/local/Cellar/go/1.25.7_1/libexec/pkg/tool/darwin_amd64/link:
running cc failed: exit status 1 /usr/bin/cc -arch x86_64 -m64 -Wl,-S
-Wl,-x -o $WORK/b583/controller.test -Qunused-arguments
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/go.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000000.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000001.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000002.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000003.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000004.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000005.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000006.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000007.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000008.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000009.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000010.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000011.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000012.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000013.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000014.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000015.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000016.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000017.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000018.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000019.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000020.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000021.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-4074891610/000022.o
-lresolv -O2 -g -O2 -g -lpthread -framework CoreFoundation -framework
Security Undefined symbols for architecture x86_64:
  "_SecTrustCopyCertificateChain", referenced from:

_crypto/x509/internal/macos.x509_SecTrustCopyCertificateChain_trampoline.abi0
in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)

FAIL github.com/google/ax/internal/controller [build failed] #
github.com/google/ax/internal/controller/task.test
/usr/local/Cellar/go/1.25.7_1/libexec/pkg/tool/darwin_amd64/link:
running cc failed: exit status 1 /usr/bin/cc -arch x86_64 -m64 -Wl,-S
-Wl,-x -o $WORK/b587/task.test -Qunused-arguments
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/go.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000000.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000001.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000002.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000003.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000004.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000005.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000006.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000007.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000008.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000009.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000010.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000011.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000012.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000013.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000014.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000015.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000016.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000017.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000018.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000019.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000020.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000021.o
/var/folders/wt/jnb6cjrj00n0ygz_p3k0zvvw0000gn/T/go-link-912479132/000022.o
-lresolv -O2 -g -O2 -g -lpthread -framework CoreFoundation -framework
Security Undefined symbols for architecture x86_64:
  "_SecTrustCopyCertificateChain", referenced from:

_crypto/x509/internal/macos.x509_SecTrustCopyCertificateChain_trampoline.abi0
in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)